services:
  octopus:
    build:
      context: .
      dockerfile: scripts/dockerfiles/Dockerfile.alpine
    image: octopus:local
    ports:
       - '8280:8080'
    volumes:
       - './data:/app/data'
    container_name: octopus
    restart: unless-stopped